<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RawPoster.UI</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CCSWE.Avalonia.Material" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RawrPoster.Infrastructure\RawrPoster.Infrastructure.csproj" />
    <ProjectReference Include="..\..\VectoPoster.Application\RawrPoster.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Post\CreatePostView.axaml.cs">
      <DependentUpon>CreatePostView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
